### ISSUE TITLE
M3uParser.parse() -> M3uParser.getAttributes() - Attribute value can't be null!

### ISSUE THREAD

**Issue by Bastian-R-dotcom** [Raiper34/m3u-parser-generator#10]
Hey, 

I debugged my react-app and i found that the error was caused by the library and in precision by the M3uParser.parse() static function calling M3uParser.getAttributes() static function. 

On a particular m3u link even if the rest of the links don't cause the error the process is stopped and we can't get just one of all the channels.

I found that the process has been stopped when all the attributes was missing in a particular m3u link.

My suggestion is during the parsing this error might be a warning about which m3u link can't be parsed and delete it but don't stop the all the process and just return a error.

Waiting for your answer. :)

**Comment by Bastian-R-dotcom** [comment]
![Uploading error.png…]()

**Comment by Bastian-R-dotcom** [comment]
<img width="1260" alt="image" src="https://github.com/Raiper34/m3u-parser-generator/assets/83319906/9cd84437-f9b1-42e3-9dba-d48b8a9282e9">

**Comment by Bastian-R-dotcom** [comment]
Update : i did an update on my api thinking she was giving m3u link in incorrect format.

<img width="681" alt="image" src="https://github.com/Raiper34/m3u-parser-generator/assets/83319906/f35e7ea0-03e2-4f43-a9b7-5fe56e7fee17">

Weirdly now when i analyze the response all is fine but the m3u parser function still logging "Attribute value can't be null !".

Maybe the problem is more critical and not cause of my data.

**Comment by Raiper34** [comment]
Hi, 
thanks for opening the issue, can you provide more details? What is the line of your playlist, you have a problem with? Can you send an example? 
Also if you want to ignore errors during parsing, you can use `ignoreErrors` parameter of the parse method. See https://m3u-parser-generator.netlify.app/classes/m3uparser#parse

**Comment by hugomcm** [comment]
Hello there,

I got the same error an found out that if the attribute starts with a space, for example -> tvg-name=" Super" it will fail.
Hope that helps to figure out the bug.

**Comment by Raiper34** [comment]
Thanks, guys, I have found the problem, I needed to turn off exception raising now, so basically parser will parse valid attributes and skip invalid ones. Commit https://github.com/Raiper34/m3u-parser-generator/commit/935497010e4714d97e1860498df3afc2cf201e87
Will be released during the weekend.

**Comment by Raiper34** [comment]
Released under v1.6.0
